### ISSUE TITLE
Blocklets should have a type, only certain blocklet can be installed from new web based blocklet management interface

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/blocklets#17]
Blocklets should have a type, only certain blocklet can be installed from new web based blocklet management interface. 

If a blocklet is a starter, or a simple demo, it makes no sense to install on a node for non-deloper users.  So we will only allow blocklets which are "matured" enough to install on ABT Node directly.  

It's the same reason, why on App Store you won't see any empty test apps, you will get some from testflights, but for those empty sampes you have to build from xcode.

**Comment by wangshijun** [comment]
Form https://blocklet.arcblock.io/blocklets.json, we have defined a `group` attribute for each blocklet, besides filtering by blocklet type is also support on our blocklet listing page.
