### ISSUE TITLE
QLDB blocklet name on blocklet page

### ISSUE THREAD

**Issue by robroyhobbs** [ArcBlock/blocklets#45]
small detail, but name should be QLDB Manager and not ocap-qldb-adapter on blocklets page to match the details.

**Comment by robroyhobbs** [comment]
https://blocklet.arcblock.io/dapp/ocap-qldb-adapter

**Comment by NateRobinson** [comment]
For the npm package, we have uploaded it to the npm registry as "ocap-qldb-adapter", but we can rename it as "QLDB Manager" in our ABT Node marketplace.
